#!/bin/bash
media="/media/winnie"
myboot="$media/MYBOOT"
myfs="$media/myfs"
out="/home/winnie/$1"
#---out dir---
bootfile="boot.scr BOOT.BIN  image.ub"
fsfile="rootfs.tar.gz"
# buse/*    --> /lib/firmware in SD card
# blite dir --> /lib/firmware in SD card
buse="buse"
blite="blite"
# bhw="system.bit pl.dtbo"
#-----------
bfirmdir="$myfs/lib/firmware"
brootdir="$myfs/home/root"
hint(){
    echo myacer2sd.sh out
}
if [ "$#" -eq 0 ]; then
    hint
    exit
fi
if [ ! -d "$out" ]; then
    echo "STOP: $out not exist"
    exit
fi
echo "$out to sdcard:"
if [ ! -d "$myboot" ]; then
    echo "STOP: $myboot not exist"
    exit
fi
cd $myboot
rm -rf *

if [ ! -d "$myfs" ]; then
    echo "STOP: $myfs not exist"
    exit
fi
echo "sudo rm -rf $myfs/*"
cd $myfs
sudo rm -rf *

cd $out
cp $bootfile $myboot
echo "sudo tar zxf $fsfile -C $myfs"
sudo tar zxf $fsfile -C $myfs
echo "----"
cd $out
# sudo cp $bhw to board
sudo cp -rf $buse/* $bfirmdir/
sudo cp -rf $blite $brootdir/
cd $bfirmdir
echo "---$(pwd)---"
ls -l *
cd $brootdir
echo "---$(pwd)---"
ls -l *
