#!/bin/bash
media="/media/winnie"
myboot="$media/MYBOOT"
myfs="$media/myfs"
out="/home/winnie/$1"
#---out dir---
bootfile="boot.scr BOOT.BIN  image.ub"
fsfile="rootfs.tar.gz"
# bhw/*    --> /lib/firmware in SD card
# blite dir --> /lib/firmware in SD card
bhw="bhw"
blite="blite"
# bhw="system.bit pl.dtbo"
#-----------
bfirmdir="$myfs/lib/firmware"
brootdir="$myfs/home/root"
bnet="$myfs/etc/network/interfaces"
hint(){
    echo "myacer2sd.sh [out dir] [net interface]"
    echo myacer2sd.sh out ori
    echo myacer2sd.sh out hw01
    echo myacer2sd.sh out hw02
}
if [ "$#" -eq 0 ]; then
    hint
    exit
fi
if [ ! -d "$out" ]; then
    echo "STOP: $out not exist"
    exit
fi
echo "$out to sdcard:"
if [ ! -d "$myboot" ]; then
    echo "STOP: $myboot not exist"
    exit
fi
cd $myboot
rm -rf *

if [ ! -d "$myfs" ]; then
    echo "STOP: $myfs not exist"
    exit
fi
echo "sudo rm -rf $myfs/*"
cd $myfs
sudo rm -rf *

cd $out
cp $bootfile $myboot
echo "sudo tar zxf $fsfile -C $myfs"
sudo tar zxf $fsfile -C $myfs
echo "----"
cd $out
# sudo cp $bhw to board
sudo cp -rf $bhw/* $bfirmdir/
sudo cp -rf $blite $brootdir/
if [ -z "$2" ]; then
  echo "Please provide an argument (ori or hw01 or hw02)"
  exit 1
fi

if [ "$2" == "ori" ]; then
  echo "Input value is ori, no action required"
elif [ "$2" == "hw01" ]; then
  sudo mv -v $bnet ${bnet}_ori
  sudo cp -v $blite/bobin/mybo_netdir/interfaces_$netintf $bnet
else
  echo "Invalid input value, please use (ori or hw01 or hw02)"
  exit 1
fi
cd $bfirmdir
echo "---$(pwd)---"
ls -l *
cd $brootdir
echo "---$(pwd)---"
ls -l *
