#!/bin/bash

# Directory to list mounted points from
dir="/media/winnie"

# Check if the directory exists
if [ ! -d "$dir" ]; then
  echo "Directory $dir does not exist."
  # exit 1
fi

# Loop through each mounted point in the specified directory
echo "-- df $dir/* --"
for mountPoint in "$dir"/*; do
  # Check if the item is a directory (mounted point)
  if [ -d "$mountPoint" ]; then
    # Use df to find the filesystem for the current mounted point
    filesystem=$(df "$mountPoint" | awk 'NR==2 {print $1}')

    # Print the mounted point and its corresponding filesystem
    echo "Filesystem: $filesystem, Mounted Point: $mountPoint"
  fi
done
message=$(cat << EOF
--- parted  ---
sudo fdisk -l /dev/sdb
sudo umount /dev/sdb*
sudo parted /dev/sdb
(parted -start)
mklabel msdos
mkpart primary fat32 1MiB 1GiB
mkpart primary ext4 1GiB 20GiB
print
quit
(parted -end)
sudo mkfs.fat -F32 /dev/sdb1 -n MYBOOT
sudo mkfs.ext4 /dev/sdb2 -L myfs
lsblk -o NAME,LABEL,SIZE,FSTYPE,MOUNTPOINT
--- dd ---
sudo umount /dev/sdb*
sudo dd if=/dev/sda of=/dev/sdb bs=4M status=progress && sync
sudo dd if=/dev/sdb1 of=/dev/sdb2 bs=4M status=progress && sync
sudo dd if=/dev/sdb of=~/sdcard.iso bs=4M status=progress && sync
sudo dd if=~/image.iso of=/dev/sdb bs=4M status=progress && sync
sudo dd if=~/myproject/ubuntu-20.04.6-desktop-amd64.iso | pv -s 4G | sudo dd of=/dev/sdb
lsblk -o NAME,LABEL,SIZE,FSTYPE,MOUNTPOINT
EOF
)

echo "$message"
