#!/bin/bash

echo "vncserver :1 -geometry 1920x1080 -depth 24"
echo "vncserver"
echo "vncserver -list"
echo "sudo ufw allow 5901"
echo "vncserver -kill :1"
echo "---client---"
echo "vncviewer 140.96.28.237:5901"

