#!/bin/bash
source mycolor
myddbg_dir="/home/winnie/mysh/myddbgdir/"
echo -e "$blue--- how to use ---$end"
cat << EOF
cd ${myddbg_dir}
[${myddbg_dir}Makefile] CFLAGS += -DMYDDBG
EOF
echo -e "$green--- exe ---$end"
echo "cat ${myddbg_dir}Makefile"
echo "make -C ../../realupdate/files/ clean"
echo "make -C ../../realupdate/files/ CFLAGS+=\" -DMYPC_TEST -DMYDDBG \""
echo "cat ${myddbg_dir}myddbg.h"
echo "cat ${myddbg_dir}tt.c"
echo -e "$green--- static lib in sub-dir ---$end"
echo "cat ${myddbg_dir}mylibdir/Makefile"
echo "cat ${myddbg_dir}mylibdir/mylib.c"
echo "cat ${myddbg_dir}mylibdir/mylib.h"

echo -e "$red--- exe:default ---$end"
echo "cat ${myddbg_dir}Makefile_df"
echo -e "$yellow--- mybook ---$end"
cat << EOF
MYDEBUG := n
MYDEBUG := y
ifeq (\${MYDEBUG}, y)
    ccflags-y   += -DDEBUG -g -ggdb -gdwarf-4 -Wall -fno-omit-frame-pointer -fvar-tracking-assignments
else
    ccflags-y   += --strip-debug
endif
EOF
echo "----"

