#!/bin/bash
mygit="/home/winnie/mysh/mygitdir"
filelist="$mygit/filelist"
filelist_nl="$mygit/filelist_nl"
mygitdiff="$mygit/mygitdiff"
log="$mygit/log"

hint(){
    error=$1
    case $error in
        "genvimdiff")
            echo "$0 diff [modified path] [ori path]"
            echo "$0 diff /home/winnie/myprojects/0615new/leo_zcu111v2021_2all /home/winnie/myprojects/leo_zcu111v2021_2all"
            ;;
        *)
            exit
            ;;
    esac

}

[ -e $filelist ] && rm $filelist
cat $filelist_nl |sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' > $filelist
echo "--vimdiff--"
if [ "$#" -eq 3 ] && [ "$1" = "diff" ]; then
    cat $filelist_nl
    echo "--------------"
    rm -rf $mygitdiff
    echo "#!/bin/bash">$mygitdiff
    while IFS= read -r line
    do
        echo "read -p \"vimdiff $2/$line $3/$line\"">>$mygitdiff
        echo vimdiff "$2/$line" "$3/$line">>$mygitdiff
        echo vimdiff "$2/$line" "$3/$line"
    done < "$filelist_nl"
    echo "--------------"
    echo "$mygitdiff"
    chmod +x $mygitdiff
    exit
else
    hint "genvimdiff"
fi
echo "---modified---"
echo $filelist_nl
echo $log
echo "---push---"
echo "git add `cat $filelist`"
echo ""
echo "git diff --staged"
echo "git commit `cat $filelist` -m \"`cat $log`\""
echo ""
echo "git lg ; git show"
echo "git push"

echo "--sub push--"
echo "winnie/12345678"
echo "sub: git push origin HEAD:master"
echo "--init--"
echo "git clone http://140.96.28.94:3000/LEO/leo_zcu111v2021_2.git"
echo "git submodule update --init --recursive"
echo "--sub update--"
echo "sub: git pull origin master"
echo "--------------"
echo "top: git submodule update --remote"
echo "top: git add project-spec"
echo "top: git commit project-spec -m \"project-spec: submodule update\""
echo "top: git push"
echo "---"
echo "git lg|grep -i spacewire"
echo "git log --follow -- components/ext_sources/kernel-source/drivers/net/spacewire.c"
echo "git log -p --follow -- components/ext_sources/kernel-source/drivers/net/spacewire.c"
echo "---git clone---"
echo "git clone --branch develop http://140.96.28.94:3000/LEO/leo_zcu111v2021_2all.git"
