#!/bin/bash
echo sudo dmesg\|tail \|grep ttyUSB
echo sudo minicom -s
echo "--[configuration]--"
echo "--Serial port setup--"
echo "A- Serial Device: /dev/ttyUSB1"
echo "E- Bps/Par/Bits: 115200 8N1"
echo "F- Hardware Flow Control: No"
echo "--Save setup as dfl--"
echo sudo minicom -D /dev/ttyUSB1
echo leave: ctrl+a x
