#!/bin/bash
cat << EOF
--- kernel config ---
/boot/config-* or /proc/config.gz
zcat /proc/config.gz > mycurrent_config

--- build-in modules ---
cat /lib/modules/$(uname -r)/modules.builtin

--- auto insert modules ---
lsmod
cat /etc/modules-load.d/modules.conf
cat /etc/modules
/lib/modules/5.10.0-xilinx-v2021.2/kernel/drivers/*
/lib/modules/5.10.0-xilinx-v2021.2/kernel/drivers/net/spacewire.ko

depmod -n
depmod --> mean update
cat /lib/modules/`uname -r`/modules.dep

--- check *.ko ---
modinfo -F vermagic spacewire.ko
uname -a

--- insert/remove modules by manual ---
modprobe spacewire
insmod spacewire
rmmod spacewire

EOF
