#!/bin/bash
if [ "$#" -eq 0 ]; then
    echo "$0 [mechine name]"
    echo "$0 acer"
    echo "$0 s149"
    echo "$0 vm"
    exit
fi
mechine=$1
myhome=/home/winnie
echo "git clone git@github.com:winnieaug22/.rcfile.git $myhome/.rcfile"
echo "rm $myhome/.bashrc $myhome/.ssh/config $myhome/.ssh/authorized_keys  $myhome/.gdbinit $myhome/.tmux.conf $myhome/.gitconfig"
echo "ln -s $myhome/mysh/mysetdir/$mechine/bashrc $myhome/.bashrc"
echo "ln -s $myhome/mysh/mysetdir/$mechine/ssh/config $myhome/.ssh/config"
echo "ln -s $myhome/mysh/mysetdir/$mechine/ssh/authorized_keys $myhome/.ssh/authorized_keys"
echo "ln --physical $myhome/mysh/mysetdir/$mechine/ssh/authorized_keys $myhome/.ssh/authorized_keys"
echo ""
echo "ln -s $myhome/mysh/mysetdir/gdbinit $myhome/.gdbinit"
echo "ln -s $myhome/mysh/mysetdir/tmux.conf $myhome/.tmux.conf"
echo "ln -s $myhome/mysh/mysetdir/gitconfig $myhome/.gitconfig"
echo ""
echo "rm $myhome/.bash_aliases  $myhome/.dir_colors "
echo "rm -r $myhome/.cgdb"
echo "ln -s $myhome/.rcfile/.bash_aliases $myhome/.bash_aliases"
echo "ln -s $myhome/.rcfile/.dir_colors $myhome/.dir_colors"
echo "ln -s $myhome/.rcfile/.cgdb $myhome/.cgdb"
echo ""
