#!/bin/bash
timeStart=$(date +%s)
homedir="/home/winnie"
toolpath="~/tool/petalinux_v2021_2"
action=$1
projName="leo_zcu111v2021_2all"
myProj=$(pwd)
# myProj="$homedir/myprojects/$projName"
out="$myProj/out"
buse="$out/buse"
img="$myProj/images/linux"
buildLog="$myProj/build/build.log"

xsaPath="$homedir/data/xsa"
forChXsa="BBDL_SPW_XXV_20240307.xsa"
# forChXsa="LCISpace111_Golden_20240611.xsa"
# forChXsa="LCISpace111_Golden_20240615.xsa"
# otherXsa="BBDL_SPW_XXV_20240307.xsa
#     LCISpace111_Golden_20240611.xsa
#     LCISpace111_Golden_20240615.xsa"
remoteUrl="http://140.96.28.94:3000/LEO/$projName.git"

plDtsi="$myProj/components/plnx_workspace/device-tree/device-tree/pl.dtsi"

check_inproj(){
    if [ ! -d "images" ]; then
        hint "notinproj"
        exit
    fi
}
hint(){
    error=$1
    case $error in
        "notinproj")
            echo no images dir
            ;;
        "all")
            echo "--- myrun ---"
            echo "[ gbitn                                                            ] "
            echo "[ clone -> chxsa xsa -> allo                                       ] "
            echo "[ fallo (include allo - qset - qbwic) ]"
            echo "[ all (include clean - config - build - pack - cp2out - cp2acer ) ] "
            echo "[ allo(include clean - config - build - pack - cp2out)            ] for myrunbatch.sh"
            echo "[ ker (include configkernle-buildkernel-cpimage2out)               ] "
            echo "[ genapp myappname (include buildapp-installapp- cpapp2outAblite)   ] "
            echo "[ qall (include qset - qbwic - qrun )                              ] "
            echo hostfwd=tcp:127.0.0.1:2222-10.0.2.15:22
            echo
            echo "---Example---"
            echo git clone $remoteUrl
            echo for change xsa:$xsaPath/$forChXsa
            echo
            echo myrun clone
            echo myrun chxsa
            echo myrun allo
            echo
            echo "--- mygit ---"
            mygitpath=$(which mygit)
            mygitdir=$mygitpath/mygitdir
            echo vim $mygitdir/filelist_nl
            echo vim $mygitdir/log
            echo
            echo ---$xsaPath---
            echo "$plDtsi"
            cat $plDtsi |grep firmware-name
            ls -l $xsaPath/
            echo ---TMPDIR: build/tmp ---
            echo "# petalinux-config -c --kernel"
            echo "build/tmp/work/zynqmp_generic-xilinx-linux/linux-xlnx/5.10+git999-r0/linux-xlnx-5.10+git999/.config"
            echo "# petalinux-config -c --rootfs"
            echo "project-spec/meta-user/conf/user-rootfsconfig"
            echo "build/tmp/work/zynqmp_generic-xilinx-linux/petalinux-image-minimal/1.0-r0/rootfs/"
            echo "# Apps/libs"
            echo "TMPDIR/zynqmp_generic-xilinx-linux"
            echo "# Cross compiler"
            echo "~/tool/petalinux_v2021_2/tools/xsct/gnu/aarch64/lin/aarch64-none/x86_64-oesdk-linux/usr/libexec/aarch64-xilinx-elf/gcc/aarch64-xilinx-elf/10.2.0"
            echo "--------------"
            echo "petalinux-create -t apps --name mytestspw --enable"
            echo "myrun genapp mytestspw"
            echo "myrun cpapp2outAblite mytestspw"
            echo "petalinux-build -c mytestspw"
            echo "petalinux-build -c mytestspw -x install"
            echo "petalinux-build -c mytestspw -x clean"
            echo
            echo "---Set according to your own petalinux path---"
            echo source $toolpath/settings.sh
            echo "---myProj path---"
            echo "$myProj"

            ;;
        *)
            hint "all"
            exit
            ;;
    esac

}
setenv(){
    source $toolpath/settings.sh
}
clean(){
    petalinux-build -x mrproper
}
chxsa(){
    forChXsa=$1
    # echo "cp $xsaPath/$forChXsa itri_system.xsa"
    cp -v $xsaPath/$forChXsa itri_system.xsa
}
genapp(){
    myapp=$1
    petalinux-config -c $myapp
    petalinux-build -c $myapp
    petalinux-build -c $myapp -x install
    cpapp2outAblite $1
}
config(){
    petalinux-config --get-hw-description itri_system.xsa --silentconfig
    # petalinux-config --get-hw-description=itri_system.xsa --silentconfig
    # petalinux-config -c kernel --silentconfig
    # petalinux-config -c u-boot --silentconfig
    # petalinux-config -c busybox --silentconfig
    # petalinux-config -c rootfs --silentconfig
}
checkerror(){
    echo "#########error:###########"
    cat $buildLog | grep -n "error: "
    echo "##########################"
}
getbitname(){
    #get bitsteam name
    local bitname=$(cat $plDtsi |grep firmware-name|grep -oP '(?<=firmware-name = ")[^";]+' )
    echo "$bitname"
}
cpapp2outAblite(){
    if [ "$#" -eq 0 ]; then
        myrun cpapp2outAblite mytestspw
        exit
    fi
    cp -vf $img/rootfs.tar.gz $out
    binPath=$(find . -name mytestspw|grep "bin/$1")
    cp -vf $binPath $out/blite/bin/
    codePath=$myProj/project-spec/meta-user/recipes-apps/$1
    cp -vrf $codePath $out/blite/code/$1
    echo "--- $out/rootfs.tar.gz ---"
    # ls -lRa $out/
    ls -l $out/
    echo "--- $out/blite/bin/$1 ---"
    ls -l $out/blite/bin/
    echo "--- $out/blite/code/$1 ---"
    ls -l $out/blite/code/
}

cp2out(){
    checkerror
    #get bitsteam name
    bitname=$(getbitname)
    mysh="$homedir/mysh"
    fpgaInit="fpgaInitok.sh"
    check_inproj

    rm -rf $out
    mkdir -p $out
    mkdir -p $buse


    cd $img
    cp BOOT.BIN image.ub rootfs.tar.gz boot.scr $out
    cp pl.dtbo $buse/
    # cp system.bit $buse/$bitname
    cp system.bit $buse/
    #Copy the actual files pointed to by soft links
    cp -aLR ~/share/blite $out

    echo "fpgabit=$bitname">$buse/$fpgaInit
    cat $mysh/fpgaInit.sh >> $buse/$fpgaInit
    echo "---$out---"
    ls -l $out/
    echo "---$out/blite---"
    ls -l $out/blite/
    echo "---$buse---"
    ls -l $buse/

}
cp2acer(){
    cd $myProj
    echo "---ssh acer:$acerOutPath---"
    # acerOutPath=tftp/out$(date "+%Y%m%d_%H%M%S")
    acerOutPath=out
    ssh -t acer "rm -rvf $acerOutPath;exit"
    scp -r out acer:$acerOutPath
    ssh -t acer "ls -l $acerOutPath/;exit"
    echo "scp $homedir/mysh/myacer2sd.sh acer:"
    echo "ssh acer"
    echo "./myacer2sd.sh out"

}
pack(){
    # petalinux-package --boot --u-boot --format BIN
    petalinux-package --force --boot --fsbl --fpga no --u-boot
    # petalinux-package --boot --fsbl images/linux/zynqmp_fsbl.elf --fpga images/linux/system.bit --u-boot
}
build(){
    petalinux-build
}
qset(){
    petalinux-package --prebuilt --fpga images/linux/system.bit
    cp ~/myprojects/xilinx-zcu111-2021.2/pre-built/linux/images/pmu_rom_qemu_sha3.elf pre-built/linux/images
}
qbwic(){
    petalinux-package --wic
    cp images/linux/petalinux-sdimage.wic pre-built/linux/images/
}
qrun(){
    petalinux-boot --qemu --prebuilt 3 --qemu-args "-net nic -net nic -net nic -net nic -net user,hostfwd=tcp:127.0.0.1:2222-10.0.2.15:22"
}
if [ "$#" -eq 0 ]; then
    hint "all"
    exit
fi
case $action in
    "gbitn")
        echo $plDtsi
        echo "firmware-name = $(getbitname)"
    ;;
    "clone")
        git clone $remoteUrl
        cd $projName
        # git submodule update --init --recursive
        # chxsa $forChXsa
        ;;
    "chxsa")
        chxsa $2
        ;;
    "all")
        config
        build
        pack
        cp2out
        cp2acer
        ;;
    "allo")
        config
        build
        pack
        cp2out
        ;;
    "pack")
        pack
        ;;
    "clean")
        clean
        ;;
    "config")
        config
        ;;
    "build")
        build
        pack
        cp2out
        cp2acer
        ;;
    "build2out")
        build
        pack
        cp2out
        ;;
    "ker")
        petalinux-config -c kernel
        petalinux-build -c kernel
        cp -f $img/image.ub $out
        ls -l $out/
        ;;
    "genapp")
        if [ "$#" -eq 0 ]; then
            hint "all"
            exit
        fi
        genapp $2
        ;;
    "cpapp2outAblite")
        cpapp2outAblite $2
        ;;
    "cp2out")
        cp2out
        ;;
    "cp2acer")
        cp2out
        cp2acer
        ;;
    "qset")
        qset
        ;&
    "qbwic")
        qbwic
        ;;
    "qrun")
        qrun
        ;;
    "qall")
        qset
        qbwic
        qrun
        ;;
    "fallo")
        config
        build
        pack
        cp2out
        qset
        qbwic
        ;;
    *)
        hint "all"
        exit
        ;;
esac
#elapsed time
timeFinish=$(date +%s);
echo
echo $((timeFinish-timeStart)) | awk '{print "elapsed time: "int($1/60)" min "int($1%60)" sec"}'
