#!/bin/bash
timeStart=$(date +%s)
homedir="/home/winnie"
toolpath="~/tool/petalinux_v2021_2"
action=$1
projName="leo_zcu111v2021_2"
myProj=$(pwd)
# myProj="$homedir/myprojects/$projName"
out="$myProj/out"
buse="$out/buse"
img="$myProj/images/linux"
buildLog="$myProj/build/build.log"

xsaPath="$homedir/data/xsa"
forChXsa="BBDL_SPW_XXV_20240307.xsa"
# forChXsa="LCISpace111_Golden_20240611.xsa"
# forChXsa="LCISpace111_Golden_20240615.xsa"
# otherXsa="BBDL_SPW_XXV_20240307.xsa
#     LCISpace111_Golden_20240611.xsa
#     LCISpace111_Golden_20240615.xsa"
remoteUrl="http://140.96.28.94:3000/LEO/$projName.git"

plDtsi="$myProj/components/plnx_workspace/device-tree/device-tree/pl.dtsi"

check_inproj(){
    if [ ! -d "images" ]; then
        hint "notinproj"
        exit
    fi
}
hint(){
    error=$1
    case $error in
        "notinproj")
            echo no images dir
            ;;
        "all")
            echo "---Set according to your own petalinux path---"
            echo source $toolpath/settings.sh
            echo
            echo "--- myrun ---"
            echo "[ gbitn                                            ] "
            echo "[ clone -> chxsa xsa -> all , build                ] "
            echo "[ all (include config - build - cp2out - cp2acer ) ] "
            echo "[ allo (include config - build - cp2out            ] for myrunbatch.sh"
            echo "[ clean                                            ] "
            echo "[ qall (include qset - qbwic - qrun )              ] "
            echo hostfwd=tcp:127.0.0.1:2222-10.0.2.15:22
            echo
            echo "---Example---"
            echo git clone $remoteUrl
            echo for change xsa:$xsaPath/$forChXsa
            echo
            echo myrun clone
            echo myrun all
            echo myrun build
            echo
            echo "--- mygit ---"
            mygitpath=$(which mygit)
            mygitdir=$mygitpath/mygitdir
            echo vim $mygitdir/filelist_nl
            echo vim $mygitdir/log
            echo
            echo ---$xsaPath---
            ls -l $xsaPath/
            echo --------------
            # echo $otherXsa
            ;;
        *)
            hint "all"
            exit
            ;;
    esac

}
setenv(){
    source $toolpath/settings.sh
}
clean(){
    petalinux-build -x mrproper
}
chxsa(){
    forChXsa=$1
    # echo "cp $xsaPath/$forChXsa itri_system.xsa"
    cp -v $xsaPath/$forChXsa itri_system.xsa
}
config(){
    petalinux-config --get-hw-description itri_system.xsa --silentconfig
    # petalinux-config --get-hw-description=itri_system.xsa --silentconfig
    # petalinux-config -c kernel --silentconfig
    # petalinux-config -c u-boot --silentconfig
    # petalinux-config -c busybox --silentconfig
    # petalinux-config -c rootfs --silentconfig
}
pack(){
    petalinux-package --force --boot --fsbl --fpga no --u-boot
}
checkerror(){
    echo "#########error:###########"
    cat $buildLog | grep -n "error: "
    echo "##########################"
}
getbitname(){
    #get bitsteam name
    local bitname=$(cat $plDtsi |grep firmware-name|grep -oP '(?<=firmware-name = ")[^";]+' )
    echo "$bitname"
}
cp2out(){
    checkerror
    #get bitsteam name
    bitname=$(getbitname)
    mysh="$homedir/mysh"
    fpgaInit="fpgaInitok.sh"
    check_inproj

    rm -rf $out
    mkdir -p $out
    mkdir -p $buse


    cd $img
    cp BOOT.BIN image.ub rootfs.tar.gz boot.scr $out
    cp pl.dtbo $buse/
    cp system.bit $buse/$bitname
    cp -r ~/share/blite $out
    # cp $mysh/myacer2sd.sh $buse

    echo "FPGA_PREFIX=$bitname">$buse/$fpgaInit
    cat $mysh/fpgaInit.sh >> $buse/$fpgaInit
    echo $out
    ls -l $out/
    ls -l $buse/

}
cp2acer(){
    cd $myProj
    echo "---ssh acer:$acerOutPath---"
    # acerOutPath=tftp/out$(date "+%Y%m%d_%H%M%S")
    acerOutPath=out
    ssh -t acer "rm -rvf $acerOutPath;exit"
    scp -r out acer:$acerOutPath
    ssh -t acer "ls -l $acerOutPath/;exit"
    echo "scp $homedir/mysh/myacer2sd.sh acer:"
    echo "ssh acer"
    echo "./myacer2sd.sh out"

}
build(){
    petalinux-build
    petalinux-package --boot --u-boot --format BIN
}
qset(){
    petalinux-package --prebuilt --fpga images/linux/system.bit
    cp ~/myprojects/xilinx-zcu111-2021.2/pre-built/linux/images/pmu_rom_qemu_sha3.elf pre-built/linux/images
}
qbwic(){
    petalinux-package --wic
    cp images/linux/petalinux-sdimage.wic pre-built/linux/images/
}
qrun(){
    petalinux-boot --qemu --prebuilt 3 --qemu-args "-net nic -net nic -net nic -net nic -net user,hostfwd=tcp:127.0.0.1:2222-10.0.2.15:22"
}
if [ "$#" -eq 0 ]; then
    hint "all"
    exit
fi
case $action in
    "gbitn")
        echo $plDtsi
        echo "firmware-name = $(getbitname)"
    ;;
    "clone")
        git clone $remoteUrl
        cd $projName
        git submodule update --init --recursive
        chxsa $forChXsa 
        ;;
    "chxsa")
        chxsa $2
        ;;
    "all")
        config
        build
        ;;
    "pack")
        pack
        ;;
    "clean")
        clean
        ;;
    "config")
        config
        ;;
    "build")
        build
        cp2out
        cp2acer
        ;;
    "build2out")
        build
        cp2out
        ;;
    "cp2out")
        cp2out
        ;;
    "cp2acer")
        cp2out
        cp2acer
        ;;
    "qset")
        qset
        ;&
    "qbwic")
        qbwic
        ;;
    "qrun")
        qrun
        ;;
    "qall")
        qset
        qbwic
        qrun
        ;;
    *)
        hint "all"
        exit
        ;;
esac
#elapsed time
timeFinish=$(date +%s);
echo
echo $((timeFinish-timeStart)) | awk '{print "elapsed time: "int($1/60)" min "int($1%60)" sec"}'
