#!/bin/bash
echo "wifi: sky"
echo "psw: brianlab   IPrange:192.168.10.xx"
echo ""
echo "psw: iclITRI2022"
cat <<EOF
------ winnie@vm[~]ssh jd1  ----
ssh v100@10.88.212.36 -p 20022    FT-dsp
ssh v100@10.88.212.36 -p 20031    CPL-dsp1
ssh v100@10.88.212.36 -p 20032    CPL-dsp2
ssh v100@10.88.212.36 -p 20033    CPL-dsp3
ssh v100@10.88.212.36 -p 20034    CPL-dsp4
ssh v100@10.88.212.36 -p 20051    UT1-dsp Cpldsp1,2 facetoFT; Cpldsp3,4 facetoUT
EOF
echo "------ winnie@vm[~]ssh jump10 ------"
echo "------ admin@jumphost[~]cat /tmp/home/root/.ssh/mycmd ---"
echo "Jump host"
echo "ssh admin@10.88.212.36 -p 9487"
echo "ssh -i /tmp/home/root/.ssh/id_j10Tdsp v100@192.168.10.31"
echo
echo DSP1\(FT\)
echo ssh v100@192.168.10.31
echo DSP2\(UT\)
echo ssh v100@192.168.10.32
echo DSP3\(FT\)
echo ssh v100@192.168.10.33
echo DSP4\(UT\)
echo ssh v100@192.168.10.34
