#!/bin/bash
echo "ssh-keygen -t ed25519 -C \"s149Tgithub\""
echo "[vm]ssh-copy-id -i id_rsa_vmTs149.pub winnie@140.96.28.149"
echo "[vm]scp id_rsa_vmTs149.pub winnie@140.96.28.149:.ssh/"
echo "[s149] cat id_rsa_vmTs149.pub >> authorized_keys"
echo
echo "eval \"\$(ssh-agent -s)\""
echo "ssh-add ~/.ssh/id_ed25519_miniTgithub"
echo "ssh-add ~/.ssh/id_ed25519_s149Tgithub_mysh"
echo "ssh-add ~/.ssh/id_ed25519_vmTgithub_mysh"
echo "ssh-add ~/.ssh/id_ed25519_acerTgithub_mysh"
echo "cat ~/.ssh/config"
echo "myboardmnt"
echo
cat << EOF
--- only access from key ---
[client]
ssh-copy-id -i id_ed25519_vmTorange.pub winnie@orange
ssh -i id_ed25519_vmTorange winnie@hilbert.csie.io -p8022
[server]
sudo vim /etc/ssh/sshd_config
 PasswordAuthentication no
 PubkeyAuthentication yes
sudo systemctl restart ssh
sudo /etc/init.d/ssh restart
EOF
