#!/bin/bash
myhome=/home/winnie/
echo "git clone git@github.com:winnieaug22/.vim.git $myhome.vim"
echo "sudo apt-get install -y curl vim vim-addon-manager vim-snippets nodejs vim-nox neovim"
# echo curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
