#!/bin/bash
echo git clone git@github.com:winnieaug22/.vim.git
echo sudo apt-get install curl
echo curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
