#!/bin/bash
echo "sudo apititude: install [tigervnc-standalone-server] [tigervnc-viewer]"
echo "vncserver :1 -localhost no"
echo "vncserver -list"
echo "vncpasswd"
echo "vncserver -kill :1"
echo "---client---"
echo "vncviewer 140.96.28.237:5901"
echo "vncviewer 140.96.28.101:5901"
