#!/bin/bash

# Check if the script is run with correct arguments
if [ $# -lt 1 ]; then
    echo "Usage: $0 <dhcp | static> [MAC_address | IP_address | any]"
    echo "Example:"
    echo "$0 dhcp "02:42:ac:11:00:01"
    echo "$0 static 192.168.0.6"
    echo "$0 dhcp any"
    exit 1
fi

# Constants
CONFIG_FILE="mybo_netdir/interfaces"
ETH0_CONFIG_START="#mynet_s"
ETH0_CONFIG_END="#mynet_e"
SYS_INTERFACE="/etc/network/interfaces"
DHCP_CONF="iface eth0 inet dhcp"
DHCP_CONF_MAC="iface eth0 inet dhcp\n   hwaddress ether"
STAT_CONF="iface eth0 inet static\n address"

# Function to check if eth0 configuration and markers exist
check_eth0_config() {
    grep -q "iface eth0" "$CONFIG_FILE" && grep -q "$ETH0_CONFIG_START" "$CONFIG_FILE" && grep -q "$ETH0_CONFIG_END" "$CONFIG_FILE"
}

# Function to update eth0 configuration for dhcp
update_eth0_dhcp() {
    local address=$1
    if [ "$address" == "any" ]; then
        sed -i "/$ETH0_CONFIG_START/,/$ETH0_CONFIG_END/ {
        /$ETH0_CONFIG_START/! { /$ETH0_CONFIG_END/!d }
        /$ETH0_CONFIG_START/a $DHCP_CONF
    }" "$CONFIG_FILE"

    elif [[ $address =~ ^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$ ]]; then
            sed -i "/$ETH0_CONFIG_START/,/$ETH0_CONFIG_END/ {
            /$ETH0_CONFIG_START/! { /$ETH0_CONFIG_END/!d }
            /$ETH0_CONFIG_START/a $DHCP_CONF_MAC $address
        }" "$CONFIG_FILE"
    else
        echo "Invalid MAC address format: $address"
        exit 1
    fi
}

# Function to update eth0 configuration for static
update_eth0_static() {
    local address=$1
    if [[ $address =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
        sed -i "/$ETH0_CONFIG_START/,/$ETH0_CONFIG_END/ {
        /$ETH0_CONFIG_START/! { /$ETH0_CONFIG_END/!d }
        /$ETH0_CONFIG_START/a $STAT_CONF $address
    }" "$CONFIG_FILE"
    else
        echo "Invalid IP address format: $address"
        exit 1
    fi
}

# Main script
if ! check_eth0_config; then
    echo "Warning: eth0 configuration or $ETH0_CONFIG_START/$ETH0_CONFIG_END markers not found in $CONFIG_FILE"
fi

case $1 in
    "dhcp")
        if [ $# -lt 2 ]; then
            echo "Usage: $0 dhcp <MAC_address | any>"
            exit 1
        fi
        update_eth0_dhcp "$2"
        ;;
    "static")
        if [ $# -lt 2 ]; then
            echo "Usage: $0 static <IP_address>"
            exit 1
        fi
        update_eth0_static "$2"
        ;;
    *)
        echo "Unknown command: $1"
        echo "Usage: $0 <dhcp | static> [MAC_address | IP_address | any]"
        exit 1
        ;;
esac

echo "---Configuration updated successfully---"
# echo "Updated $CONFIG_FILE:"
echo cat "$CONFIG_FILE"
# echo "Backing up $SYS_INTERFACE to ${SYS_INTERFACE}_ori"
echo mv "$SYS_INTERFACE" "${SYS_INTERFACE}_ori"
# echo "Copying $CONFIG_FILE to $SYS_INTERFACE"
echo cp "$CONFIG_FILE" "$SYS_INTERFACE"
# echo "Restarting networking service..."
echo /etc/init.d/networking restart
