#!/bin/bash
read -p "vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/Makefile leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/Makefile"
vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/Makefile leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/Makefile
read -p "vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/mytestspw.c leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/mytestspw.c"
vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/mytestspw.c leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/mytestspw.c
read -p "vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/packet_transfer.c leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/packet_transfer.c"
vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/packet_transfer.c leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/packet_transfer.c
read -p "vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/packet_transfer.h leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/packet_transfer.h"
vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/packet_transfer.h leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/packet_transfer.h
read -p "vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/pkgs.h leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/pkgs.h"
vimdiff leo/project-spec/meta-user/recipes-apps/mytestspw/files/pkgs.h leo_zcu111v2021_2all/project-spec/meta-user/recipes-apps/mytestspw/files/pkgs.h
